### ISSUE TITLE
Application error Heroku

### ISSUE THREAD

**Issue by BeaGaete** [IIC2143-2018-1/syllabus-2#5]
Tengo el siguiente error en heroku:
###### WARNING:
       No Procfile detected, using the default web server.
       We recommend explicitly declaring how to boot your server process via a Procfile.
       https://devcenter.heroku.com/articles/ruby-default-web-server
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> console, rake, web, worker
-----> Compressing...
       Done: 31.7M
-----> Launching...
       Released v4
       https://shielded-temple-71747.herokuapp.com/ deployed to Heroku

Heroku hace el deploy y me entrega el link de la app, pero el helloworld no se muestra, solo se muestra 
 "Application error" y en los logs aparece lo de más arriba. Hice el archivo Procfile y puse las cosas que dice el link, pero aún así sigue saliendo "Application error" (la app sí funciona en el local host)
¿Alguien sabe que puede estar pasando?

**Comment by fdoflorenzano** [comment]
Hola, como comentamos en reunión, las dudas de proyecto en el repositorio de proyecto.
