### ISSUE TITLE
Recorrección I2 

### ISSUE THREAD

**Issue by josemlira** [IIC2143-2018-1/syllabus-2#7]
Hola! Cuándo estarán las recorrecciones de la I2?

**Comment by haroldmuller** [comment]
Hola,
Deberían estar a fines de esta semana, sino a primera hora el día lunes.

**Comment by josemlira** [comment]
Aún no están :c

**Comment by haroldmuller** [comment]
Ya se subieron todas las recorrecciones pendientes.
